FROM zhouminjie4589/php-7.4-fpm:1.3

# 支持ZIP
#RUN apt install libzip-dev
#RUN docker-php-ext-install zip

# 支持BZ2
#RUN apt install libbz2-1.0 libbz2-dev -y
#RUN docker-php-ext-install bz2

# 支持bcmath
#RUN docker-php-ext-install bcmath


